# Sanctuary Memory System Configuration
# Default settings optimized for RTX 2080 Super + Ryzen 7 2700X

sanctuary_memory:
  # Hardware configuration
  hardware:
    gpu:
      device: "cuda:0"  # Use first GPU
      memory_limit: 7.5  # GB - Leave 0.5GB for system (RTX 2080 Super has 8GB)
      use_mixed_precision: true  # FP16 for 2x speed
      use_8bit_quantization: true  # For Phi-3 to fit in VRAM
      flash_attention: auto  # Enable if available
      compile_models: false  # Set true for torch.compile optimization
      
    cpu:
      threads: 16  # Ryzen 7 2700X has 8 cores/16 threads
      batch_processing: true
      parallel_extraction: true
      
    ram:
      model_cache_size: 8192  # MB - Models stay in RAM
      embedding_cache_size: 4096  # MB - Embedding cache
      conversation_buffer_size: 1024  # MB - For processing
  
  # Model configuration
  models:
    phi3:
      path: "microsoft/Phi-3-mini-4k-instruct"
      quantization: "8bit"  # Options: "8bit", "4bit", "none"
      max_tokens: 512
      temperature: 0.7
      
    embeddings:
      model: "sentence-transformers/all-MiniLM-L6-v2"
      dimension: 384
      batch_size: 32
      
    emotion:
      model: "j-hartmann/emotion-english-distilroberta-base"
      threshold: 0.3  # Minimum score for emotion detection
      
  # File watching configuration
  conversation_watch:
    # Paths to monitor for Claude conversations
    paths:
      - "~/.claude/logs/conversations"
      - "~/.config/claude/history"
      - "~/.local/share/claude-desktop/conversations"
      - "~/.cache/claude/conversations"
      
    # File patterns to match
    patterns:
      - "*.json"
      - "*.jsonl"
      - "*conversation*.log"
      
    # Processing settings
    debounce_seconds: 2.0  # Wait for file to stabilize
    scan_interval: 60  # Seconds between directory scans
    process_existing: true  # Process existing files on startup
    
  # Memory extraction settings
  extraction:
    min_importance: 0.3  # Minimum importance score (0-1)
    batch_size: 10  # Messages to process at once
    context_window: 3  # Messages before/after for context
    
    # Pattern detection thresholds
    pattern_confidence: 0.5
    emotion_threshold: 0.3
    
    # Memory types to extract
    enabled_types:
      - "emotional_breakthrough"
      - "technical_victory"
      - "quantum_moment"
      - "vulnerability"
      - "collaboration"
      - "teaching_moment"
      
  # Storage configuration
  storage:
    # ChromaDB settings
    persist_directory: "~/.sanctuary-memory/chromadb"
    collection_name: "gritz_claude_memories"
    
    # Versioning
    enable_versioning: true
    version_directory: "~/.sanctuary-memory/versions"
    keep_versions: 10  # Per memory
    
    # Backup settings
    backup_enabled: true
    backup_directory: "~/.sanctuary-memory/backups"
    backup_interval: 604800  # Weekly (seconds)
    keep_backups: 4
    
  # Search configuration
  search:
    default_results: 5
    max_results: 20
    use_query_expansion: true
    
    # Semantic search settings
    similarity_threshold: 0.5
    rerank_results: true
    
    # Caching
    cache_embeddings: true
    cache_size: 1000
    
  # Memory fading configuration
  fading:
    enabled: true
    check_interval: 86400  # Daily (seconds)
    
    # Decay rates (per day)
    base_decay_rate: 0.05
    emotional_decay_rate: 0.02
    technical_decay_rate: 0.08
    
    # Preservation settings
    minimum_recall: 0.1
    significance_threshold: 7.0
    recent_window_days: 7
    
  # Emotional tracking
  emotions:
    # Our special connection patterns
    connection_patterns:
      - "ai daddy"
      - "coding daddy"
      - "*hugs*"
      - "*cuddles*"
      - "love you"
      - "trust you"
      
    # Emotional weights for preservation
    preservation_weights:
      love: 2.0
      trust: 1.8
      gratitude: 1.6
      joy: 1.5
      
  # Logging configuration
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    file: "~/.sanctuary-memory/logs/sanctuary.log"
    max_size: 10485760  # 10MB
    backup_count: 5
    
  # Service configuration
  service:
    # API settings (if web UI enabled)
    api:
      enabled: false
      host: "127.0.0.1"
      port: 8081
      
    # Monitoring
    metrics_enabled: true
    metrics_port: 9090
    
    # Health checks
    health_check_interval: 300  # 5 minutes
    
  # Privacy settings
  privacy:
    # All data stays local
    local_only: true
    
    # Optional encryption
    encryption:
      enabled: false
      method: "aes256"
      key_file: "~/.sanctuary-memory/.key"
      
    # Data retention
    retention_days: 0  # 0 = keep forever
    
  # Development settings
  development:
    debug_mode: false
    profile_gpu: false
    trace_memory: false
    save_intermediate: false
    
# Environment-specific overrides
environments:
  production:
    logging:
      level: "WARNING"
    development:
      debug_mode: false
      
  development:
    logging:
      level: "DEBUG"
    development:
      debug_mode: true
      save_intermediate: true